import os

SECRET_KEY = _SECRET_KEY
SQLALCHEMY_DATABASE_URI = _SQLALCHEMY_DATABASE_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_SIZE = 200
UPLOAD_FOLDER = os.getcwd() + "/static/dekonts"
